### ISSUE TITLE
Calculating the pyramid with colorSpace set to gray results in two black channels

### ISSUE THREAD

**Issue by JN-Jones** [elucideye/acf#36] opened 2018-03-20 16:07 UTC
For a project of mine I've to work with colorSpace set to gray. While `chnsCompute` seems to respect that and returns only one color channel, `chnsPyramid` calculates only one channel but returns three channels where the second and third channel are simply black. The original matlab toolbox seems to discard those two channels, would be nice if this library could do the same.

**Comment by JN-Jones** [comment] 2018-03-23 14:35
Little update: It seems that `chnsCompute` ignores this too, however if I'm inputting a grayscale image I only get one colorchannel. Looks like the number of input channels is used instead of the number of requested channels.

**Comment by headupinclouds** [comment] 2018-03-23 15:11
https://github.com/elucideye/acf/blob/17b8da4c72290a55ecfcca7899dbdd1da061ce80/src/lib/acf/chnsCompute.cpp#L139

```
int Detector::chnsCompute(const MatP& IIn, const Options::Pyramid::Chns& pChnsIn, Detector::Channels& chns, bool isInit, MatLoggerType pLogger)
```

I'll add a few notes to help track the relevant code sections.  

There is a field `Field<Color> Options::Pyramid::Chns::pColor` in the input structure passed to `chnsCompute(...)` and the input `MatP` image comes with a dimension: `int MatP::channels()`.

```
                struct Color
                {
                    Field<int> enabled;
                    Field<double> smooth;
                    Field<std::string> colorSpace;

                    void merge(const Color& src, int mode);
                    friend std::ostream& operator<<(std::ostream& os, const Color& src);

                    template <class Archive>
                    void serialize(Archive& ar, const uint32_t version);
               };
```

In your case first scenario, you are passing in a 3 channel RGB image and are requesting `colorSpace == "gray"`.  It should return a single color channel, but instead you are getting 3 channels, where the first one is grayscale.  We don't want the second two.

Assuming that is correct, I can try to reproduce it this weekend.  Feel free to send a fix if you have one.


https://github.com/elucideye/acf/blob/1c9fa310e2d743f7b91d44c1b1016e40376eb183/src/lib/acf/chnsCompute.cpp#L222

```
        rgbConvert(I, I, p.colorSpace, true);
```

:point_up: It looks like `I` is use as an input and output type here.  I believe the output type should be (re)allocated using the channel count of the colorspace specified by `p.colorSpace`:
 
https://github.com/elucideye/acf/blob/1c9fa310e2d743f7b91d44c1b1016e40376eb183/src/lib/acf/rgbConvert.cpp#L109

```
int Detector::rgbConvert(const MatP& IIn, MatP& J, const std::string& colorSpace, bool useSingle, bool isLuv)
{
    // <SNIP>
    if (!IIn.empty() && (flag != 1) && (flag != 4))
    {
        rgbConvertMex(IIn, J, flag, useSingle);
    }
```

https://github.com/elucideye/acf/blob/1c9fa310e2d743f7b91d44c1b1016e40376eb183/src/lib/acf/toolbox/rgbConvertMex.cpp#L385-L387
```
    J.create(I.size(), I.depth(), I.channels());
    float* pJ = J.ptr<float>();
    rgbConvert(const_cast<float*>(pI), pJ, I.size().area(), I.channels(), flag, float(nrm));
```

**Comment by JN-Jones** [comment] 2018-03-24 07:30
>In your case first scenario, you are passing in a 3 channel RGB image and are requesting colorSpace == "gray". It should return a single color channel, but instead you are getting 3 channels, where the first one is grayscale. We don't want the second two.

Exactly. If I simply change the input image from a rgb image to a grayscale image without modifying any other param I get only one color channel as output. For now I'm simply removing those two channels after converting them to `std::vector<cv::Mat>` but obviously that's far from efficient.

**Comment by headupinclouds** [comment] 2018-04-04 15:25
This should be fixed in the latest version.

**Comment by headupinclouds** [comment] 2018-05-01 01:58
Okay, thanks for the update.  I'll re-open this and sort through it more carefully.

**Comment by JN-Jones** [comment] 2018-05-22 07:07
Any Update on this one? Really would like to see an official fix for this instead of my workaround.

**Comment by headupinclouds** [comment] 2018-05-23 02:23
I've added a [date](https://github.com/elucideye/acf/milestone/1) for this one and will work on a fix this weekend.  The notes above are helpful.  For conciseness, Can you also share a small Matlab code sample to illustrate the expected behavior?  Something like [this](https://github.com/elucideye/acf/issues/72#issuecomment-390421998)

```
I=imread('dodecagon.png') * 255; % force [0 ... 255]
pPyramid=chnsPyramid();
P2=chnsPyramid(I,pPyramid);
splitA = num2cell(P2.data{1}, [1 2]);
P2_montage = horzcat(splitA{:});
imwrite(P2_montage, '/tmp/acf_matlab.png');
```

**Comment by JN-Jones** [comment] 2018-05-23 07:13
Sure though the dodecagon seems to result in an black image anyways so I've used an image from the dataset I'm using:

![traffic](https://user-images.githubusercontent.com/1917879/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8.jpg)

```matlab
I=imread('traffic.jpg');
pPyramid=chnsPyramid();
pPyramid.pChns.pColor.colorSpace = 'gray';
P2=chnsPyramid(I,pPyramid);
splitA = num2cell(P2.data{1}, [1 2]);
P2_montage = horzcat(splitA{:});
imwrite(P2_montage, '/tmp/acf_matlab.png');
```

![acf_matlab](https://user-images.githubusercontent.com/1917879/40408939-8c780bde-5e69-11e8-8cae-8cfa441a9b8e.png)

**Comment by headupinclouds** [comment] 2018-05-28 21:50
```
polly.py --toolchain xcode --config Release --fwd HUNTER_CONFIGURATION_TYPES=Release --install
_install/xcode/bin/acf-pyramid --input=${HOME}/Downloads/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8.jpg --output=/tmp --colorspace gray
montage -tile 8x -border 0 -geometry +0+0 /tmp/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8_*_*_*.png /tmp/pyramid_gray.jpg
```

![pyramid_gray](https://user-images.githubusercontent.com/554720/40630314-aa686eb0-629f-11e8-87d8-43e69174100a.jpg)

**Comment by headupinclouds** [comment] 2018-05-28 21:52
```
polly.py --toolchain xcode --config Release --fwd HUNTER_CONFIGURATION_TYPES=Release --install
_install/xcode/bin/acf-pyramid --input=${HOME}/Downloads/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8.jpg --output=/tmp --colorspace luv
montage -tile 10x -border 0 -geometry +0+0 /tmp/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8_*_*_*.png /tmp/pyramid_luv.jpg
```

![pyramid_luv](https://user-images.githubusercontent.com/554720/40630329-da344182-629f-11e8-84c1-9399e96dbaf7.jpg)

**Comment by headupinclouds** [comment] 2018-05-28 21:53
```
polly.py --toolchain xcode --config Release --fwd HUNTER_CONFIGURATION_TYPES=Release --install
_install/xcode/bin/acf-pyramid --input=${HOME}/Downloads/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8.jpg --output=/tmp --colorspace rgb
montage -tile 10x -border 0 -geometry +0+0 /tmp/40408926-7e6499ae-5e69-11e8-9573-3fc8f15385c8_*_*_*.png /tmp/pyramid_rgb.jpg
```

![pyramid_rgb](https://user-images.githubusercontent.com/554720/40630355-118dd72e-62a0-11e8-9269-09a80d6ae129.jpg)

**Comment by headupinclouds** [comment] 2018-05-28 22:01
@JN-Jones: The above were created with https://github.com/elucideye/acf/pull/80 which adds `--colorspace` to the `acf-pyramid` console utility, but the actual lib updates are already merged.  Let me know if that doesn't address your use case.

**Closed by headupinclouds** 2018-05-28 22:01 UTC
Labels: bug

**Comment by JN-Jones** [comment] 2018-05-29 07:01
Seems to be fixed, thanks
